---
title: "Untitleda6_task4_kirsten_white"
author: "Kirsten White"
date: "11/23/2021"
output: html_document
---

```{r setup, message = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(ggplot2)
library(plotly)

```

```{r}
# Read in the data & clean it up 

mono_lake_data <- read_csv(here("data", "mono_lake_annual_levels.csv"), skip = 5) %>% # skips the first 5 rows (unnecessary)
  clean_names() %>%
  drop_na(vertical_change)
```
```{r}
# Data wrangling

level_change <- mono_lake_data %>%
  select(year, vertical_change, stable_level, lake_level_feet_above_sea_level)

ggplot(data = level_change, aes(x = year)) + 
  #geom_line() +
  geom_line(aes(y = lake_level_feet_above_sea_level), color = "navyblue")+
  #geom_line(aes(y = vertical_change), color = "red3")+
  scale_y_continuous(breaks = c(6375, 6385, 6395, 6405, 6415, 6425))+
  scale_x_continuous(breaks = c(1850, 1875, 1900, 1925, 1950, 1975, 2000, 2017)) + 
  geom_hline(yintercept = 6392, color = "skyblue2", size = 0.9)+
  labs(x = "Year", 
       y = "Water Level (ft above sea level)", 
       title = "Mono Lake Level Change (1851 - 2017)") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))+
  theme(axis.title = element_text(size = 10, face = "bold"))
 # annotate(geom = "text", x = "1987", label = "x")
       
```

