---
title: "Chi Squared"
author: "Kirsten White"
date: "11/22/2021"
output: html_document
---

```{r setup, message = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# Attach Packages

library(tidyverse)
library(here)
library(broom)
library(janitor)
```

```{r}
# Read in the data 

conservation_survey <- read_csv(here("data", "conservation_survey.csv"))

```
```{r}
# Create a subset containing only ENV_ID and POL_OR columns
conservation_subset <- conservation_survey %>%
  select(ENV_ID, POL_OR) %>%
  mutate(POL_PARTY = case_when
         (POL_OR %in% c("1","2", "3") ~ "Conservative", 
           POL_OR %in% c("5", "6", "7") ~ "Liberal")) %>%
          drop_na() %>% # conservative 1-3; liberal 5-7; exclude 4, 8, 9
  mutate(ENV_ID = case_when(
         ENV_ID == "1" ~ "Yes", 
         ENV_ID == "2" ~ "No", 
         ENV_ID == "3" ~ "Unsure"))
```

```{r}
# Create a finalized table showing the counts and proportions of liberal and conservative respondents who responded yes, no, and unsure

# Find the counts 
conservation_subset %>%
  count(POL_PARTY) %>%
  arrange(-n)

# Find counts by political party affiliation and response (to environmentalist q) 
conservation_subset %>%
  count(POL_PARTY, ENV_ID)

# Return counts (from above) in a contingency table format 
environmental_counts <- conservation_subset %>%
  tabyl(POL_PARTY, ENV_ID)

# Show percentages 
environmental_proportions <- environmental_counts %>%
  adorn_percentages() %>%
  adorn_pct_formatting((digits = 2)) %>%
  adorn_ns()

# Convert to contingency table 

environmental_table <- environmental_counts %>%
  column_to_rownames(var = "POL_PARTY")

# Chi-squared - asking: is identifying as an environmentalist truly independent of the political party one identifies with 
environ_x2 <- chisq.test(environmental_table)
environ_x2

# Write out chi-sq info in tidy format (in order to refer to the values in-line)
environ_tidy <- tidy(environ_x2)

```


# Mini Intro 
Describing the survey data, the question you’re answering, and the method you’ll use

# Finalized Table of Counts & Proportions (w/ table caption)

# 2 - 3 sentence summary of the hypothesis test results and major takeaways

# Add the data citation 
